# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c0a9c47b9f6dafc63e082ef51a382ba03524b96c3a01a4ae5304f6ebe23f0be74a4dd52adfafa43af155b080957c676ec3411d9034f0a7e5550350c48884b00

test:
  secret_key_base: 955cd5e4ab81f8a2649efa0e1d53042e0b3b14f4ac90f5645a76cd7792872ddf89ac4e82ef792b8aa5c74e6ab51d618b759a542903cc50eb093abe81186642c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
